# ANALISIS DIAGNOSTIK FAKTOR PENYEBAB & PEMODELAN PREDIKTIF TINGKAT PUBLIKASI JURNAL DOSEN ITS

## Import Library

In [49]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
from plotly.offline import iplot
import os 
import glob
from sklearn.cluster import KMeans
!pip3 install joypy
import joypy

Collecting joypy
  Downloading joypy-0.2.6-py2.py3-none-any.whl.metadata (812 bytes)
Requirement already satisfied: numpy>=1.16.5 in /opt/anaconda3/lib/python3.11/site-packages (from joypy) (1.26.4)
Requirement already satisfied: scipy>=0.11.0 in /opt/anaconda3/lib/python3.11/site-packages (from joypy) (1.11.4)
Requirement already satisfied: pandas>=0.20.0 in /opt/anaconda3/lib/python3.11/site-packages (from joypy) (2.2.1)
Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.11/site-packages (from joypy) (3.8.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>=0.20.0->joypy) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>=0.20.0->joypy) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.11/site-packages (from pandas>=0.20.0->joypy) (2023.3)
Requirement already satisfied: contourpy>=1.0.1 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib->joypy) (1.2.0)
Requirement already satisfied: cycler>=0.10 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib->joypy) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib->joypy) (4.25.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib->joypy) (1.4.4)
Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib->joypy) (23.1)
Requirement already satisfied: pillow>=8 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib->joypy) (10.2.0)
Requirement already satisfied: pyparsing>=2.3.1 in /opt/anaconda3/lib/python3.11/site-packages (from matplotlib->joypy) (3.0.9)
Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->joypy) (1.16.0)
Downloading joypy-0.2.6-py2.py3-none-any.whl (8.6 kB)
Installing collected packages: joypy
Successfully installed joypy-0.2.6

## Load Dataset

In [54]:
# Load the data
# Data is stored in 'data_journal'
data_journal = pd.read_csv('author_book.csv', delimiter =';')
data_journal

,id_buku,isbn,title,penulis_full,tempat,penerbit,year,sinta_id,_sys_date_processed,category,nama_versi_kepegawaian,nama_versi_akademik,jenis_pegawai,jurusan,fakultas
0,38569,9786025022128,KIMIA 1,Taslim Ersam...[et al.],Surabaya,"Media Bersaudara, CV",2018,28963,2022-11-10 00:07:24,buku ajar,"Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.","Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.",Dosen,Kimia,Fakultas Sains dan Analitika Data
1,36208,9786024011499,Karakterisasi Struktur Padatan,"Didik Prasetyoko, Hamzah Fansuri, Yatim Lailun...",Yogyakarta,Deepublish,2016,28963,2022-11-10 00:07:24,buku referensi,"Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.","Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.",Dosen,Kimia,Fakultas Sains dan Analitika Data
2,92375,9786233900171,Pengantar pembelajaran mesin,Penulis Mohammad Isa Irawan,NaN,CV. Pustaka Ilalang,2021,29056,2022-11-10 00:07:24,NaN,"Prof. Dr. Drs. Mohammad Isa Irawan, M.T.","Prof. Dr. Drs. Mohammad Isa Irawan, M.T.",Dosen,Matematika,Fakultas Sains dan Analitika Data
3,43161,9786026715951,Bioinformatika : perspektif matematika pada an...,Oleh Siti Amiroch...[et al.],Lamongan,CV. Pustaka Ilalang,2018,29056,2022-11-10 00:07:24,NaN,"Prof. Dr. Drs. Mohammad Isa Irawan, M.T.","Prof. Dr. Drs. Mohammad Isa Irawan, M.T.",Dosen,Matematika,Fakultas Sains dan Analitika Data
4,96684,9786237060772,Pengolahan sinyal digital,"Suwadi, Titiek Suryani",Bandung,Refika Aditama,2020,29086,2022-11-10 00:07:24,NaN,"Prof.Dr.Ir. Titiek Suryani, M.T.","Prof.Dr. Ir. Titiek Suryani, M.T.",Dosen,Teknik Telekomunikasi,Fakultas Teknologi Elektro dan Informatika Cerdas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,85279,9786021062999,Separuh,Mushonnifun Faiz Sugihartanto,NaN,Sunrise,2016,6755916,2022-11-10 00:07:24,NaN,"Mushonnifun Faiz Sugihartanto, S.T., M.Sc.","Mushonnifun Faiz Sugihartanto, S.T., M.Sc.",Dosen,Manajemen Bisnis,Fakultas Desain Kreatif dan Bisnis Digital
363,139460,9786239953003,Analisa Kekuatan Konstruksi Deck Kapal Tongkan...,Santi Frestiqauli,Semarang,Dewa Publisher,2022,6775395,2022-11-10 00:07:24,buku referensi,NaN,NaN,NaN,NaN,NaN
364,139459,9786239953058,Engineering Critical Assessment Instalasi Pipa...,Santi Frestiqauli,Bandung,Dewa Publisher,2022,6775395,2022-11-10 00:07:24,buku referensi,NaN,NaN,NaN,NaN,NaN
365,139474,9786232125766,Perspective [sumber elektronik],Santi Frestiqauli,Semarang,Qauli Publisher,2018,6775395,2022-11-10 00:07:24,buku monograf,NaN,NaN,NaN,NaN,NaN
366,139471,9786232129559,#Volunteerisme,Santi Frestiqauli,Semarang,Qauli Publisher,2014,6775395,2022-11-10 00:07:24,buku monograf,NaN,NaN,NaN,NaN,NaN

In [51]:
data_journal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 367 entries, 0 to 366
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_buku                 367 non-null    int64
 1   isbn                    367 non-null    object
 2   title                   367 non-null    object
 3   penulis_full            364 non-null    object
 4   tempat                  316 non-null    object
 5   penerbit                367 non-null    object
 6   year                    367 non-null    int64
 7   sinta_id                367 non-null    int64
 8   _sys_date_processed     367 non-null    object
 9   category                137 non-null    object
 10  nama_versi_kepegawaian  358 non-null    object
 11  nama_versi_akademik     358 non-null    object
 12  jenis_pegawai           358 non-null    object
 13  jurusan                 358 non-null    object
 14  fakultas                358 non-null    object
dtypes: int64(3), object(12)
memory usage: 43.1+ KB

## Informasi Kolom dan Baris

In [53]:
print(data_journal.columns)
print(data_journal.index)

Index(['id_buku', 'isbn', 'title', 'penulis_full', 'tempat', 'penerbit',
       'year', 'sinta_id', '_sys_date_processed', 'category',
       'nama_versi_kepegawaian', 'nama_versi_akademik', 'jenis_pegawai',
       'jurusan', 'fakultas'],
      dtype='object')
RangeIndex(start=0, stop=367, step=1)

In [60]:
# Filtering Each Faculty
# Faculty of Science (Fakulatas Sains dan Analitika Data)
data_journal_fsad = data_journal[data_journal['fakultas'] == 'Fakultas Sains dan Analitika Data']
data_journal_fsad

,id_buku,isbn,title,penulis_full,tempat,penerbit,year,sinta_id,_sys_date_processed,category,nama_versi_kepegawaian,nama_versi_akademik,jenis_pegawai,jurusan,fakultas
0,38569,9786025022128,KIMIA 1,Taslim Ersam...[et al.],Surabaya,"Media Bersaudara, CV",2018,28963,2022-11-10 00:07:24,buku ajar,"Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.","Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.",Dosen,Kimia,Fakultas Sains dan Analitika Data
1,36208,9786024011499,Karakterisasi Struktur Padatan,"Didik Prasetyoko, Hamzah Fansuri, Yatim Lailun...",Yogyakarta,Deepublish,2016,28963,2022-11-10 00:07:24,buku referensi,"Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.","Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.",Dosen,Kimia,Fakultas Sains dan Analitika Data
2,92375,9786233900171,Pengantar pembelajaran mesin,Penulis Mohammad Isa Irawan,NaN,CV. Pustaka Ilalang,2021,29056,2022-11-10 00:07:24,NaN,"Prof. Dr. Drs. Mohammad Isa Irawan, M.T.","Prof. Dr. Drs. Mohammad Isa Irawan, M.T.",Dosen,Matematika,Fakultas Sains dan Analitika Data
3,43161,9786026715951,Bioinformatika : perspektif matematika pada an...,Oleh Siti Amiroch...[et al.],Lamongan,CV. Pustaka Ilalang,2018,29056,2022-11-10 00:07:24,NaN,"Prof. Dr. Drs. Mohammad Isa Irawan, M.T.","Prof. Dr. Drs. Mohammad Isa Irawan, M.T.",Dosen,Matematika,Fakultas Sains dan Analitika Data
34,38569,9786025022128,KIMIA 1,Taslim Ersam...[et al.],Surabaya,"Media Bersaudara, CV",2018,5972678,2022-11-10 00:07:24,buku ajar,"Prof. Dr.rer.nat. Fredy Kurniawan, S.Si., M.Si.","Prof. Dr.rer.nat. Fredy Kurniawan, S.Si., M.Si.",Dosen,Kimia,Fakultas Sains dan Analitika Data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
343,48017,9786027430945,"SMART CITY: KONSEP, MODEL, & TEKNOLOGI",Bangun Muljo Sukojo... [et al.],Surabaya,Asosiasi Sistem Informasi Indonesia (AISINDO),2019,6649424,2022-11-10 00:07:24,lainnya,"Hamdan Dwi Rizqi, S.Si., M.Si.","Hamdan Dwi Rizqi, S.Si., M.Si.",Dosen,Kimia,Fakultas Sains dan Analitika Data
344,38569,9786025022128,KIMIA 1,Taslim Ersam...[et al.],Surabaya,"Media Bersaudara, CV",2018,6649424,2022-11-10 00:07:24,buku ajar,"Hamdan Dwi Rizqi, S.Si., M.Si.","Hamdan Dwi Rizqi, S.Si., M.Si.",Dosen,Kimia,Fakultas Sains dan Analitika Data
351,71998,9786025542527,Pengembangan bahan karbon dari biomassa,"Darminto, Malik Anjelh Baqiya, Retno Asih",Surabaya,ITS Press,2018,6711373,2022-11-10 00:07:24,NaN,"Retno Asih, S.Si., M.Si., Ph.D.","Retno Asih, S.Si., M.Si., Ph.D.",Dosen,Fisika,Fakultas Sains dan Analitika Data
355,55414,9789793980270,"Penyajian informatif tabel, grafik dan statistik","Muhammad Arif Tiro, Muhammad Ahsan",NaN,Andira Karya Mandiri Publisher,2014,6724761,2022-11-10 00:07:24,NaN,"Dr. Muhammad Ahsan, S.Si.","Dr. Muhammad Ahsan, S.Si.",Dosen,Statistika,Fakultas Sains dan Analitika Data
358,98853,9786239727710,Bakteriologi spesies kosmopolit,"penulis, Arif Luqman ... [et al.] ; editor, Ar...",NaN,Departemen Biologi Institut Teknologi Sepuluh ...,2021,6728295,2022-11-10 00:07:24,NaN,"Dr.rer.nat. Arif Luqman, S.Si., M.T.","Dr.rer.nat. Arif Luqman, S.Si., M.T.",Dosen,Biologi,Fakultas Sains dan Analitika Data

In [59]:
data_journal_fsad.head()

,id_buku,isbn,title,penulis_full,tempat,penerbit,year,sinta_id,_sys_date_processed,category,nama_versi_kepegawaian,nama_versi_akademik,jenis_pegawai,jurusan,fakultas
0,38569,9786025022128,KIMIA 1,Taslim Ersam...[et al.],Surabaya,"Media Bersaudara, CV",2018,28963,2022-11-10 00:07:24,buku ajar,"Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.","Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.",Dosen,Kimia,Fakultas Sains dan Analitika Data
1,36208,9786024011499,Karakterisasi Struktur Padatan,"Didik Prasetyoko, Hamzah Fansuri, Yatim Lailun...",Yogyakarta,Deepublish,2016,28963,2022-11-10 00:07:24,buku referensi,"Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.","Prof. Hamzah Fansuri, S.Si., M.Si., Ph.D.",Dosen,Kimia,Fakultas Sains dan Analitika Data
2,92375,9786233900171,Pengantar pembelajaran mesin,Penulis Mohammad Isa Irawan,NaN,CV. Pustaka Ilalang,2021,29056,2022-11-10 00:07:24,NaN,"Prof. Dr. Drs. Mohammad Isa Irawan, M.T.","Prof. Dr. Drs. Mohammad Isa Irawan, M.T.",Dosen,Matematika,Fakultas Sains dan Analitika Data
3,43161,9786026715951,Bioinformatika : perspektif matematika pada an...,Oleh Siti Amiroch...[et al.],Lamongan,CV. Pustaka Ilalang,2018,29056,2022-11-10 00:07:24,NaN,"Prof. Dr. Drs. Mohammad Isa Irawan, M.T.","Prof. Dr. Drs. Mohammad Isa Irawan, M.T.",Dosen,Matematika,Fakultas Sains dan Analitika Data
34,38569,9786025022128,KIMIA 1,Taslim Ersam...[et al.],Surabaya,"Media Bersaudara, CV",2018,5972678,2022-11-10 00:07:24,buku ajar,"Prof. Dr.rer.nat. Fredy Kurniawan, S.Si., M.Si.","Prof. Dr.rer.nat. Fredy Kurniawan, S.Si., M.Si.",Dosen,Kimia,Fakultas Sains dan Analitika Data

In [61]:
data_journal_fsad.info()

<class 'pandas.core.frame.DataFrame'>
Index: 93 entries, 0 to 358
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id_buku                 93 non-null     int64
 1   isbn                    93 non-null     object
 2   title                   93 non-null     object
 3   penulis_full            92 non-null     object
 4   tempat                  86 non-null     object
 5   penerbit                93 non-null     object
 6   year                    93 non-null     int64
 7   sinta_id                93 non-null     int64
 8   _sys_date_processed     93 non-null     object
 9   category                59 non-null     object
 10  nama_versi_kepegawaian  93 non-null     object
 11  nama_versi_akademik     93 non-null     object
 12  jenis_pegawai           93 non-null     object
 13  jurusan                 93 non-null     object
 14  fakultas                93 non-null     object
dtypes: int64(3), object(12)
memory usage: 11.6+ KB

In [62]:
data_journal_fsad.describe()

             id_buku         year      sinta_id
count      93.000000    93.000000  9.300000e+01
mean    73339.612903  2016.946237  5.781407e+06
std     40246.479407     4.559666  1.237019e+06
min       505.000000  1994.000000  2.896300e+04
25%     38569.000000  2016.000000  5.976202e+06
50%     59292.000000  2018.000000  5.980047e+06
75%     96540.000000  2020.000000  5.998915e+06
max    143617.000000  2022.000000  6.728295e+06

In [86]:
# Checking measures of availability in column 'fakultas'
number_data_journal = data_journal_fsad['fakultas']

# Range
data_range = np.ptp(number_data_journal)

# Standard Deviation    
# data_std = np.std(data_journal_fsad['tahun'])

#Variance
# data_var = np.var(data_journal_fsad['tahun'])

# Interquartile Range (IQR)
# Q1 = data_journal_fsad['tahun'].quantile(0.25)
# Q3 = data_journal_fsad['tahun'].quantile(0.75)
# IQR = Q3 - Q1

# Show Resluts
# print('Number of data:', number_data_journal)
# print('Range:', data_range)
# print('Standard Deviation:', data_std)
# print('Variance:', data_var)
# print('Interquartile Range (IQR):', IQR)

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U33'), dtype('<U33')) -> None